services:
  todo-api:
    build: .
    container_name: todo_api_container
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app # Sync your local directory with the container
      - /usr/src/app/node_modules # Avoid conflicts with node_modules in the container
    command: npm run dev && ts-node prisma/seed.ts
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_SCHEMA: ${DATABASE_SCHEMA}
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
    depends_on:
      - postgresql-db
  postgresql-db:
    image: postgres:16.4
    container_name: postgres_container
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
